### ISSUE TITLE
"Get Requests" test fails with 403... sometimes

### ISSUE THREAD

**Issue by bollwyvl** [MarketSquare/robotframework-requests#200]
This is probably due to trying to hit https://api.github.com, which is being hit [here](https://github.com/bulkan/robotframework-requests/blob/fb771fbaf0950853d52532847f67c206dfdb58cc/tests/testcase.txt#L14).

Perhaps to avoid this Once And For All, the test cases shouldn't even call out to real URLs, instead using a local fake server with a self-signed cert, which is how i've often ended up having to use it.

Thoughts?

**Comment by vkosuri** [comment]
@bollwyvl I think agree with you, If possible could you create PR for this request?

**Comment by vkosuri** [comment]
@bollwyvl I think ok with httpbin or others

**Comment by bulkan** [comment]
I've disabled the failing tests for the moment pending a fix

**Comment by bollwyvl** [comment]
Sorry, haven't had a chance to get back to this... I should push up the
stuff that works against a local, self signed httpbin... Not sure about the
other providers... I guess make them non critical?

**Comment by lucagiove** [comment]
I integrated a local http server that actually is a partial local instance of httbin all tests will be moved to use the local one to reduce latency and possible rate limits.

**Comment by bollwyvl** [comment]
Fantastic! Thanks!
