### ISSUE TITLE
post data have same key

### ISSUE THREAD

**Issue by kanchi240** [MarketSquare/robotframework-requests#207]
Hello,

My post data have multiple same key name with different value, see below example:

import RequestsLibrary
 _request = RequestsLibrary.RequestsKeywords()
url='http://httpbin.org/post'
 _request.create_session(alias='CBS', url='http://httpbin.org')
r=  _request.post_request(alias='CBS',uri='/post',data={'interests': ['football', 'basketball']})
print r.request.body
r=  _request.post_request(alias='CBS',uri='/post',data=[('interests', 'football'), ('interests', 'basketball')])
print r.request.body

output:
interests=%5B%27football%27%2C+%27basketball%27%5D
interests=football&interests=basketball

ONLY the previous solution worked, but all the above two solutions should work, see quickstart guide below:

http://docs.python-requests.org/en/master/user/quickstart/
https://stackoverflow.com/questions/23384230/how-to-post-multiple-value-with-same-key-in-python-requests

**Comment by lucagiove** [comment]
This should be the same as #320 that will be fixed with 0.9 version you can already try the alpha version
