### ISSUE TITLE
multipart/form-data boundary problem

### ISSUE THREAD

**Issue by aluckin3** [MarketSquare/robotframework-requests#213]
Hi guys,
I want to use post method but im getting this error: 
`u'message': u'Multipart: Boundary not found', u'code': u'UnexpectedError'`
Here is code:
```${imported_file}=   get file   ${RESOURCES}${/}a.xml
&{directory_file}=    Create Dictionary    file=${imported_file}
${response}=   post request   ${service_name}   /${version}/${uri}  headers=${headers}  files=${directory_file}
set test variable  ${response}
```

Before that i added Content-Type=multipart/form-data in headers

Notice that restlet/postman add this boundary automatically for example in restlet you have:

`multipart/form-data; boundary=----WebKitFormBoundaryA0GEnwiQ2lKg4mal`

**Comment by vkosuri** [comment]
did your tests failed without boundary header?

**Comment by aluckin3** [comment]
Yes

**Comment by hsuan51** [comment]
Have you solved this?
Do we need to calculate boundary by ourselves?

**Comment by lucagiove** [comment]
I did a test myself and it's working have a look at the source of [Post Multipart Test code](https://github.com/MarketSquare/robotframework-requests/blob/de384ec75557137049c071061b485810269520dd/atests/test_post_multipart.robot).
It's something requests library does automatically but you have not to add on your own the Multipart headers.

**Comment by lucagiove** [comment]
Let me know whether this helps now:
https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#POST%20a%20Multipart-Encoded%20File

**Comment by hsuan51** [comment]
@lucagiove Thanks! It's help me a lot.
The important thing is that we don`t need to set content-type when post multipart.
RequestLibrary will provide it automatically.
