### ISSUE TITLE
Multiple fields in one multipart/form-data request part

### ISSUE THREAD

**Issue by jaasal** [MarketSquare/robotframework-requests#218]
I am trying to use requestslibrary to upload some files, goal is to achieve this:
```
------WebKitFormBoundary61N9vqJ7380nh6iv
Content-Disposition: form-data; name="files"; filename="photo-2.jpeg"
Content-Type: image/jpeg


------WebKitFormBoundary61N9vqJ7380nh6iv
Content-Disposition: form-data; name="fileId"

b3duLWZpbGVzL2ZmZmZmZmZmYTQyNDVmODAvMjAxNTY*
------WebKitFormBoundary61N9vqJ7380nh6iv
Content-Disposition: form-data; name="extract"

false
------WebKitFormBoundary61N9vqJ7380nh6iv--
```

and now I have this:
```
${data}=    Evaluate    {'files': open("C:/testautomation/resources/Assets/photo-2.jpeg", 'r+b'), 'extract': (None, 'false'), 'fileId': (None, 'b3duLWZpbGVzL2ZmZmZmZmZmYTQyNDVmODAvMjAxNTY*')}
${result}=  Post Request  rest  ${url}  headers=${HEADERS}  files=${data}
```

I _THINK_ that the only bit I am missing is the "Content-Type: image/jpeg" from the first part, but how on earth I can add that? Currently the file gets uploaded, but it is not considered to be a image file.

**Comment by lucagiove** [comment]
You just have to pass the files in a list structure like shown here:
https://2.python-requests.org/en/master/user/advanced/#post-multiple-multipart-encoded-files

And do not add any content-type headers otherwise requests won't add the boundaries header

**Comment by lucagiove** [comment]
I added a test example here: https://github.com/MarketSquare/robotframework-requests/blob/master/atests/test_post_multipart.robot

**Comment by lucagiove** [comment]
> @lucagiove what if the multiple parts are not all files?

I've no idea, also the origina library uses as example a list of files passed to files= parameter

**Comment by webloginwu** [comment]
I have the same requirement as @emanlove,  robotframwork don't support multiple parts that are not all files.
I got the below error:
The server cannot or will not process the request, only one file support

**Comment by thangtcq** [comment]
I got it, this is my code.

```
User Profile
    [Arguments]    ${req_token}    ${req_fullname}    ${req_birthday}    ${req_avatar}    ${req_captcha}=req_captcha
    ${image}=  Evaluate   {'avatar': ('avatar.png', open('${EXECDIR}/ResourceProvider/avatar.png', 'rb'), 'image/jpeg')}
    &{body}    Create Dictionary    full_name=${req_fullname}    birthday=${req_birthday}    captcha=${req_captcha}
    &{headers}    Create Dictionary    Authorization=Token ${req_token}
    ${resp}    POST On Session    session    /api/v1/user    files=${image}    data=${body}    headers=${headers}
```
