### ISSUE TITLE
Deprecate To Json keyword in favor of response.json attribute

### ISSUE THREAD

**Issue by ppazos** [MarketSquare/robotframework-requests#219]
I have seen tests supporting ${jsondata}= To Json ${resp.content}

But couldn't find a way to get data out of the jsondata

For instance, I want to check if a specific value is at a path in the json tree, how can that be achieved?

**Comment by trogdor259** [comment]
`${jsondata["key"][0]["another_key"]}`

**Comment by ppazos** [comment]
thanks @trogdor259 is there any documentation about that API? for instance, can I do something like ${jsondata["key"].length} ? Or how to ask is an attribute exists in the JSON like ${jsondata["key"].exists} ?

**Comment by lucagiove** [comment]
you can directly get the dictionary with ${resp.json()}
http://docs.python-requests.org/en/master/user/quickstart/#json-response-content

**Comment by lucagiove** [comment]
To be honest I don't see the point of using To Json keyword since the response already has .json attribute.

**Comment by andreagubellini** [comment]
Hi, I've opened [this](https://github.com/MarketSquare/robotframework-requests/pull/297) PR related to this issue.

**Comment by mayribeirofernandes** [comment]
https://github.com/MarketSquare/robotframework-requests/pull/297#issuecomment-769954902
