### ISSUE TITLE
Different order of parameters in Get Request keyword compared to all the others (this change was and will be backward incompatible)

### ISSUE THREAD

**Issue by virpara** [MarketSquare/robotframework-requests#232]
There was addition of `json` parameter in the `Get Request` keyword, but it was added in the argument before `params` parameter. It means that the positional argument which user expects to be set as `params` actually becomes `json`.

Previous signature `get_request(self, alias, uri, headers, json, params, ...)`
Backward compatible signature should be `get_request(self, alias, uri, headers, params, json, ...)`

**Comment by lucagiove** [comment]
I guess now it's too late to change since would break again the compatibility

**Comment by lucagiove** [comment]
Actually also the PUT keyword has not the same order of parameters as the POST :(

**Comment by andreagubellini** [comment]
What's the plan on this ticket? How do you guys want to manage it?

**Comment by lucagiove** [comment]
As you can see the new Keywords structure followed completely the original requests order so this will be handled by 0.8 release.
