### ISSUE TITLE
Error accessing https call with self signed certificate

### ISSUE THREAD

**Issue by AliAliKhan83** [MarketSquare/robotframework-requests#238]
Hi,
I am calling the creation session on https service which is hosted in local intranet with a self signed certificate. I can easily access the rest service via soupui or chrome but when trying to access the service from the robotframework-request library I am getting below error.

'ProxyError('Cannot connect to proxy.', error(10054, 'An existing connection was forcibly closed by the remote host'))':

The same service is hosted as http and when I replace https with it, the service works fine. May I know how can I call https without getting the proxy error?

**Comment by lucagiove** [comment]
Are your python version and requests library up to date?

Have your https session been created just before the request?
Maybe try to paste more context of your usage.

Do you have any error on the server side?
That error seems to be low level related to tcp handshake.

Cheers,
Luca

Il gio 19 set 2019, 11:37 AliAliKhan83 <notifications@github.com> ha
scritto:

**Comment by lucagiove** [comment]
no answer
