### ISSUE TITLE
Allow passing auth param to create client cert session

### ISSUE THREAD

**Issue by AMaciaga** [MarketSquare/robotframework-requests#245]
In my project I need test that uses session with both certificate and auth. Could you modify Create Client Cert Session keyword to accept auth parameter instead of setting it to None by default? Or create new keyword that allows that?

**Comment by AMaciaga** [comment]
Could you tell me, when you plan to release correction for this issue and is there any demand for specific python version.

**Comment by lucagiove** [comment]
As soon as I've some spare time :) I'll work on it and no there are no needs for specific python versions.

**Comment by robinmatz** [comment]
I would like to contribute to this issue. What I need to know is, should the ``auth`` be of HTTP Basic auth? Or should it be like in ``Create Custom Session`` where any auth type is accepted, but user has to take care of creating the ``auth`` object?

**Comment by lucagiove** [comment]
> I would like to contribute to this issue. What I need to know is, should the `auth` be of HTTP Basic auth? Or should it be like in `Create Custom Session` where any auth type is accepted, but user has to take care of creating the `auth` object?

I think "Create Client Cert Session" should have also `auth` parameter since all the other keywords have it should be basic auth like the others.
The only problem is that it would be a breaking change.

**Comment by lucagiove** [comment]
@robinmatz I published a 1.0a1 version with your changes, I hope you can use the library now.
I'll introduce further breaking changes later on this version.
