### ISSUE TITLE
Sessionless keywords

### ISSUE THREAD

**Issue by lucagiove** [MarketSquare/robotframework-requests#252]
Fire and forget requests without any previously declared session.
Original requests library already supports this so would be nice to handle it in the same way.

~~We can try to have this feature in place with current keyword structure by triggering the one shot session when alias is `None`.~~ Cannot be done otherwise also uri should be not mandatory.

According to #257 these requests keywords should fail by default if status code returns an error.
I think the parameters should be the same as _On Session_ keywords besides the missing alias.

**`GET`**     _`http://example.pl/resource`_    _`expected_status=401`_
**`POST`**     _`http://example.pl/resource`_    _`expected_status=401`_
...

**Problems:**

1.  what to do with the session, probably try to recycle the logic of original library 
2.  shall the session be accessible by RF?

**Solution:**

1. most probably it's a good idea to not create a session accessible from RF and leave it handled by requests library to keep thing sample and avoid side effects
2. most probably, if you need it, the right way to use it is to create a session before

**Comment by eternalconcert** [comment]
Would you assign this one to me? Sounds quite interesting to me.

**Comment by lucagiove** [comment]
Hi, that's part of the 0.7 milestone where I plan to change totally the keywords and their behavior.
Before starting to code I'd like to have a better idea how will the final keywords structure will be.
Anyhow I'd like to share some ideas and discuss how to change 0.7 layout, are you on RF slack? we can start a discussion in #requests channel and maybe report then on github.

**Comment by lucagiove** [comment]
By the way if you want to contribute immediately there are a couple of issues "accepted" where some help of debugging / fixing would be appreciated.

**Comment by eternalconcert** [comment]
Hey, yes I am on RF slack. It would be nice to discuss the topic.

I also will check the accepted issues if there is something I can contribute to.
