### ISSUE TITLE
Main keywords should fail by default if status code returns an error

### ISSUE THREAD

**Issue by lucagiove** [MarketSquare/robotframework-requests#257]
### Problems:
- failure reports are not clear because requests failure are evaluated later when parsing the response
- to solve the above problem you should always assert for status adding more verbosity in keywords
- sometime if the payload/status is not evaluated you cannot realize that a requests

### Possible solutions:
- By default each requests should fail if status code >=400 :+1: 
- In each requests keywords you can expect a resulting status code :+1: 

### Considerations:
To solve the above problems probably a non retro compatible change is needed so the keywords design needs to be carefully considered

### Accept all statuses to avoid failures
If you have a custom keyword that returns a response where the status is evaluated later you cannot have e request that never fails.
In below example Test Case A cannot be executed properly because it will fail in the `GET On Session`

```
Custom Request Keyword
    ${resp}=  GET On Session  session  /endpoint   params
    Return ${resp}

Test Case A
    ${resp_a}=    Custom Request Keyword   param_error
    Status Should Be   400   ${resp_a}

Test Case B
    ${resp_b}=    Custom Request Keyword   param_ok
    Status Should Be   OK    ${resp_b}
```
     
`None` cannot be used because is the default that expects anything that is not an error

### Possible solution:
Passing a special string like "anything" or "all" seems the most feasible and accepted solution :+1:

**Comment by humbienri** [comment]
This seems a rather odd ask.  Fail all Keywords?  Assuming you are using all keywords? Plus doesn't this assume that the request and the check/assertion will be in the same file?

**Comment by lucagiove** [comment]
Hi @humbienri thanks for your feedback but I don't get your question.
The idea is something like:
`Get Request And Fail On Error    connection    http://example.ex/404`
By default this keyword will fail in case status code is 404.
Or maybe `Get Request    connection    http://example.ex/404    expected_code=404`
If you don't specify nothing as expected_code if code is >=400 keyword will fail.
