### ISSUE TITLE
Split keywords in different class/files

### ISSUE THREAD

**Issue by lucagiove** [MarketSquare/robotframework-requests#270]
In order to avoid having one single big file here is the idea of splitting and inherit from different classes:

```
RequestsKeywords (common requests and sessionless keywords)
    |_ SessionKeywords (session creation and data)
        |_ DeprecatedKeywords (old keywords that need sessions)
        |_ RequestsOnSessionKeywords (new keywords that use sessions)
        
RequestsLibrary (extends RequestsOnSessionKeywords, DeprecatedKeywords)
```

Another option is to rely on the [PythonLibCore](https://github.com/robotframework/PythonLibCore) to split files.

### Development
first experiment: https://github.com/MarketSquare/robotframework-requests/tree/class-splitting
current development: https://github.com/MarketSquare/robotframework-requests/tree/0.8-class-splitting

**Comment by andreagubellini** [comment]
I believe this feature has already been done. Should we close it?

**Comment by lucagiove** [comment]
Still need to move deprecated keywords
