### ISSUE TITLE
Unable to send XML payload in the form of key - value pair for a POST request in robot framework

### ISSUE THREAD

**Issue by Manisha0421** [MarketSquare/robotframework-requests#274]
Hi,

I have to make a POST request through SOAP to a URL by providing the payload as an XML file in the form of a key value pair, like xml: "content of XML file"

The code is able to read the XML file correctly and displays the content of the file but when making the POST request, it gives "

HTTP/1.1 400 Unable to get data [ xml is required]"

Note: This request is being sent using robot framework script;
The same request is working fine with the same XML when sending the request via Postman.

Robot file code:
Create Session soap ${URLService} verify=False
${file_data} Get Binary File ${Transaction_Request}
Log ${file_data}
${files}= Create Dictionary xml ${file_data}
${headers}= Create Dictionary Content-Type=application/xml
${resp}= Post Request alias=soap uri=${URLComponentDateRangeAPI} files=${files} headers=${headers}
Log ${resp.content}
${root}= Parse Xml ${resp.content}
log ${root.tag}

Output for POST request:

		<ccare>
		<response><menu name="" ref=""></menu>
						<page title="" pageRef="">
						<table resizable="true">
						<tableHead currentPage="1" nbPages="1" nbRecords="1">
						<cell size="200" filter="no-filter"><text>ErrorMessage</text></cell>
						</tableHead>
						<tableData>
						<row><cell size="200" filter="no-filter"><text>HTTP/1.1 400 Unable to get data [ xml is required ]</text></cell></row>
					</tableData>
					</table>
					</page>
					</response>
		</ccare>

Can anybody help resolve this issue.

Thanks & Regards

**Comment by lucagiove** [comment]
I saw this discussed already on slack, have you found a solution?

**Comment by lucagiove** [comment]
No answer
