### ISSUE TITLE
On Session keywords

### ISSUE THREAD

**Issue by lucagiove** [MarketSquare/robotframework-requests#276]
### Standard requests on existing sessions
Similar format of keywords as current 0.6 but with:
- the same **minimum required parameters** as original requests library
- the same parameter order as original requests library #232
- with default failing if response has an status code >= 400 #257 

**`GET On Session`**    _`session-name`_    _`/resource`_   _`expected_status=401`_
**`POST On Session`**    _`session-name`_    _`/resource`_   _`expected_status=401`_

### Development
This branch has a custom feature for @chilispa:
https://github.com/MarketSquare/robotframework-requests/tree/fail-on-status-and-new-keywords
@chilispa is dogfooding this feature

Original feature branch was:
https://github.com/MarketSquare/robotframework-requests/tree/new-keywords

There is already a proposed new branch for 0.8 version, the idea is to have many pre-releases for that version:
https://github.com/MarketSquare/robotframework-requests/tree/0.8

**Comment by acaovilla** [comment]
Me, Nicola And Roberta start working here
