### ISSUE TITLE
Positional url with params are wrongly parsed in On Session keywords

### ISSUE THREAD

**Issue by lucagiove** [MarketSquare/robotframework-requests#288]
Example:
`${resp}=       GET On Session    ${GLOBAL_ANONYMOUS_SESSION}    entertainment/api/v1/merchandise?content=${content_id}`

For some reason (probably because of the =) the second parameter is not evaluated properly:
`Keyword 'RequestsLibrary.Get On Session' expected 2 to 5 non-named arguments, got 1.`

If I remove the **kwargs in the python keyword than it works.

Workaround solution use url= as prefix

**Comment by pekkaklarck** [comment]
This is a Robot Framework feature [explained in the User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-keyword-arguments-kwargs). When a keyword accepts `**kws`, all arguments containing `=` are considered to be in `name=value` syntax. If you want to avoid that, you need to use escape syntax like `\=`.

**Comment by lucagiove** [comment]
Thank you @pekkaklarck ! I'm wondering whether there is anything I can do on library level to intercept this and at least give a warning/message to the user, but I think not.

**Comment by pekkaklarck** [comment]
Probably the best that can be done is documenting this with keywords that accept **kws. That's how Robot's standard libraries handle this:
http://robotframework.org/robotframework/latest/libraries/Process.html#Run%20Process
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Call%20Method

**Comment by lucagiove** [comment]
In the end I added a decorator that parses the aruguments and raise a more explanatory error

```
def warn_if_equal_symbol_in_url(func):
    def decorator(*args, **kwargs):
        try:
            args[2]
        except IndexError:
            if 'url' not in kwargs:
                logger.warn("You might have an = symbol in url."
                            " You better place 'url=' before, example: 'url=/your-url/foo?param=a'"
                            " or use '/your-url/foo  params=param=a' or escape it")

        return func(*args, **kwargs)
    decorator.__name__ = func.__name__
    decorator.__doc__ = func.__doc__
    return decorator
```
