### ISSUE TITLE
Support POST request with file list

### ISSUE THREAD

**Issue by andrewda** [MarketSquare/robotframework-requests#292]
With Requests, I can do something like the following to post multiple files. This request includes two files with the "bar" key, which will both be sent in the request.

```python
import requests

requests.post('http://0.0.0.0:7627/endpoint',
              files=[('foo', open('something.txt', 'rb')),
                     ('bar', open('data1.zip', 'rb')),
                     ('bar', open('data2.zip', 'rb'))])
```

As far as I can tell, this is currently not supported in RequestsLibrary, as only a dictionary can be passed as file data. Adding support for a list of files like this would be great!

**Comment by andrewda** [comment]
I actually got this working by using

```
    ${files}=      Evaluate   [('foo', open('${file1}', 'rb')), ('bar', open('${file2}', 'rb')), ('bar', open('${file3}', 'rb'))]
    ${resp}=       Post Request      myapi      /endpoint   files=${files}
```

There's gotta be a better way than using `Evaluate` that I'm missing, though...

**Comment by lucagiove** [comment]
This is possible with keyword: [Get File For Streaming Upload](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#Get%20File%20For%20Streaming%20Upload)
