### ISSUE TITLE
requests_ntlm not installed while installing library

### ISSUE THREAD

**Issue by adiralashiva8** [MarketSquare/robotframework-requests#305]
`Create Ntlm Session` got failed until user install `requests_ntlm` library explicitly

**Comment by lucagiove** [comment]
An error should be shown in case of missing library, check it out: 
https://github.com/MarketSquare/robotframework-requests/blob/ae9c3bbf4d01a110c19115b77abaa56872c20575/src/RequestsLibrary/RequestsKeywords.py#L351

**Comment by adiralashiva8** [comment]
Im getting Nameerror: HttpNtlmAuth is undefined

**Comment by lucagiove** [comment]
I see I might be able to reproduce it should be a try / except not an if statement
