### ISSUE TITLE
Status Should Be keywork can't check 400-series errors

### ISSUE THREAD

**Issue by joelwhitehouse** [MarketSquare/robotframework-requests#311]
# Backround

I'm using `robotframework-requests` to regression test an API.  It's worked out well except for when I attempted to use the `Status Should Be` keyword to assert that an endpoint returned a 400-series error, like `400` or `404`.

# Steps to Reproduce

Run the following in a `.robot` file:

    *** Settings ***
    Library      RequestsLibrary
    
    *** Test Cases ***
    Perform Check After GET
        Create Session    example_session    https://google.com
        ${resp}=  GET On Session  example_session  /404.html
        Status Should Be 404

# Expected Behavior

This test should pass.

# Actual Behavior

The test fails with the message:

	*FAIL*  HTTPError: 404 Client Error: Not Found for url: https://google.com/404.html
    	

# Investigation

The `Status Should Be` consists of a single source line of code, a call to `self._check_status()`[0].  This would normally provide the pass/fail judgement that's expected of a "Should Be" style keyword.  

However, the `GET On Session` keyword, which is not a "Should Be" style keyword, is calling the `self._check_status()` function as well [1].  This would be okay if the optional `expected_status` keyword was set, but it's not, so `GET On Session` proceeds to make a pass/fail decision for our test despite the fact that we haven't specified to it what our pass/fail criteria are.

	
[0]: https://github.com/MarketSquare/robotframework-requests/blob/d850e11e5873b3b54d6349e5102703597b7b4faa/src/RequestsLibrary/RequestsKeywords.py#L38
[1]: https://github.com/MarketSquare/robotframework-requests/blob/d850e11e5873b3b54d6349e5102703597b7b4faa/src/RequestsLibrary/RequestsOnSessionKeywords.py#L50

# Recommendation

The `self._check_status()` function in both `GET On Session` and `POST On Session` should be made conditional on `not expected_status == None`.

I would be happy to provide a pull request.

**Comment by lucagiove** [comment]
Hi, thanks for the detailed report but this how the implicit assert has been intended.
If you want to test a specific error case you could pass GET On Session ... expected_status=400 and if you want to make it more explicit you could pass expected_status=any and the use Status Should Be.

Hope this is more clear now.

**Comment by joelwhitehouse** [comment]
Thanks for your consideration!  

I opened this issue focused on a specific behavior, but I'd like to make a broader appeal to architecture: within `robotframework` and across its most popular libraries, keywords serve only one of two basic functions:

1. constructing state
2. making assertions about the state

This convention is consistent across robot libraries from BuiltIn [0] to the venerable SeleniumLibrary [1], which cleanly separate state construction (`Create Dictionary`, `Open Browser`) from assertions about state (`Should Be Equal As Numbers`, `Page Should Contain`.)  

What the `GET/POST On Session` keywords is combining the two concerns.  Keeping them separated is an expected part of the robot developer experience.  After working with RobotFramework, you wouldn't expect the `Open Browser` keyword to succeed at opening your browser but then claim it failed because by default it made assertions about the content loaded into the browser.  Likewise, `Create Dictionary` shouldn't cause a test to fail due to an assertion about the contents of the dictionary you created.  After years of using builtin and third party keywords, this two-step process is common, and expected.  In the same way, it is genuinely unexpected for a keyword like 'GET On Session' to execute a perfectly valid GET request, receive a valid response, and then _fail anyway_ due to assertions it's making about what the response ought be.  

Per your response, it is possible to override these assertions and cause the `GET/POST On Session` keywords to follow the conventional behavior, but the default behavior is still surprising and inconsistent with conventional RobotFramework design.  Ideally, if the assertions are to be left in the `GET/POST On Session` keywords, they should be disabled by default and enabled only by request.

While it's a hassle to make breaking changes, `robotframework-requests` is already nicely setup for this, with several plannedks future breaking changes found within the deprecated keywords [2] file.  The practice of making assertions by default in state-constructing keywords would also be an excellent behavior to deprecate and eliminate in a future release.

`robotframework-requests` has a clean and useful set of keywords, and I would like to see used just as widely within the RobotFramework community as the `requests` library is within the python community.  Keeping its keyword behaviors consistent with convention will help decrease developer confusion and increase its rate of adoption.

 
 [0]: http://robotframework.org/robotframework/latest/libraries/BuiltIn.html
 [1]: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
 [2]: https://github.com/MarketSquare/robotframework-requests/blob/master/src/RequestsLibrary/DeprecatedKeywords.py#L17

**Comment by lucagiove** [comment]
Hi Joel,

thank you for your suggestion.
To be honest this new behavior that I call "implicit assert" it has been actually broadly discussed: on github, on slack, on specific meetups, at robotframework foundation meetings. The 0.8 pre-release version has been available since months and no one complained about this.

I agree that asserts has been always separated in robotframework but it's also true that the new Browser Library has a similar behavior so let me say that this is an emergent pattern.

Actually those fail aren't even asserts but more execution errors, exactly like you can get errors if a DB communication breaks down here if a requests return a status code >= 400 the keyword returns an error.

The idea comes from our company experience where we often had log errors saying: "dictionary X does not contain something" but that wasn't the real problem. After some debugging you realize that a previous HTTP request (step) failed so the further execution was compromised.

Once we introduced this feature we had many tests failing that we thought were working properly while steps were failing without anyone finding out.

Hope this clarifies the choice reason.
