### ISSUE TITLE
Misleading documentation in requests URI

### ISSUE THREAD

**Issue by zulus** [MarketSquare/robotframework-requests#313]
I tried to use `Get Request` keyword in 0.8, but something is broken, I'm no able to put URI, it's support only path.

In documentation it's information about "URI" not path so I tryied: `Get Request    sess    https://mydomain.com/test`, but result is `https://mydomain.com/https://mydomain.com/test`. Same problem with `Get On Session`

**Comment by lucagiove** [comment]
If you add the full URI when the session is created you just have to complete with the endpoint for each requests.

    Create Session sess https://mydomain.com
    GET On Session sess /test

What's the point of adding the full URI in GET On Session keyword?

**Comment by zulus** [comment]
I collected all urls on page and want check response status one by one. With python 2 I was able to do this via http lib. For python 3 I found this lib and documentation  „Get Request    sess    URI”, but looks like it misleading me

**Comment by lucagiove** [comment]
Ok I see the point I might make it more clear in documentation.
You can strip the common url use it during session creation and then just the partial url in single requests keywords.

I'm going to implement in 0.9 session less keywords that might suite your case.

**Comment by lucagiove** [comment]
I now join session url and requests url with urllib urljoin

**Comment by lucagiove** [comment]
Check it out by installing the new version:

`pip install robotframework-requests --pre`

**Comment by cloutierjo** [comment]
This actually cause a new issue. We did use the lib in this way:

    Create Session sess https://mydomain.com/dev
    GET On Session sess /test

Which does a GET on https://mydomain.com/dev/test , Now it's doing it on https://mydomain.com/test which obviously fail. I'm not sure if the way we were using it should be supported going forward, but at least it should be marked as breaking change in the 0.9 version. Thought I would prefer to keep the old behaviour as it makes it easy to switch our test between different environment that does not always have the same base path (/dev might be /test or /...).

**Comment by lucagiove** [comment]
I think there is a big bug here I missed a test case

**Comment by lucagiove** [comment]
Ok now the behavior is more rfc compliant but slightly different from the past.
To have the right behavior you've to write the test in this way:

```
Create Session sess https://mydomain.com/dev
GET On Session sess /test
```
