### ISSUE TITLE
Slowness when REST call returns big JSON

### ISSUE THREAD

**Issue by jbenech** [MarketSquare/robotframework-requests#318]
First of all, thank you for this library !

I have an issue when I perform REST call that returns big (1.5M) json. The time to process is about 17s
After investigation it appears that the issue is that the server does not set any `Charset` in the response.
It seems that when the charset is not set by the server, the request library use chardet (see https://requests.readthedocs.io/en/master/user/advanced/#encodings) and chardet is known to be slow on big content.
With the request library the workaround is to set the `response.encoding` before accessing to `response.text`.

=> I would like to known if there is a way with the robot library to provide the charset as a parameter in the `Get On Session`  in order to avoid the (very) slow charset detection ?

(I try to put an `Accept-Charset` in the request header for this call, but even with additional request attribute, this the server does not return any Charset attribute)

**Comment by lucagiove** [comment]
I don't think this is possible.
Best option would be for the server to return the proper encoding in headers to avoid guess algorithm.
