### ISSUE TITLE
utf8_urlencode changes the value of params

### ISSUE THREAD

**Issue by szabolcstoth** [MarketSquare/robotframework-requests#320]
Hej everyone!

In Python using `requests` I can set the same query parameters with different values like this:
```python
parameters = {'something': [1, 2, 3, 4, 5]}
r = requests.get('http://example.com/page', params=parameters)
```

With this dictionary I will get the following:
```python
print(r.request.path_url)
/page?something=1&something=2&something=3&something=4&something=5
```

I would like to achieve the same with RequestsLibrary:
```robotframework
*** Test Cases ***
First Test Case
    @{something}=    Create List    1    2    3    4    5
    &{parameters}=    Create Dictionary
    ...    something    ${something}
    Create Session
    ...    session_one
    ...    https://www.example.com
    GET On Session
    ...    session_one
    ...    /page
    ...    params=${parameters}

*** Settings ***
Library    RequestsLibrary
```

But it does not works since it creates the following URL:
`https://www.example.com/page?something=%5B%271%27%2C+%272%27%2C+%273%27%2C+%274%27%2C+%275%27%5D`

As I can see, the `GET On Session` keyword uses `_common_request` function, which uses `utf8_urlencode` on the value of `params` which causes this behavior. Is there any solution for this what I am not ware of or can we handle this as a bug?

**Comment by lucagiove** [comment]
I always had the felling that parsing the params was wrong. I'm not sure whether this is going to break things but actually that's how original requests library works so... why changing it?
I'm going to remove it in the next alpha and see whether someone complains.

**Comment by lucagiove** [comment]
I'd like to have a failing test for this but not sure. Maybe comparing params in `url` vs params in `param` if you have a failing test would help.

**Comment by lucagiove** [comment]
I reproduced and fixed it if you think it's fine I'm gonna merge and build a new 0.9a2 version

**Comment by szabolcstoth** [comment]
Thanks for the fix, I also tested it with my example, it seems it works as is should! 👍

**Comment by lucagiove** [comment]
Thanks, give it a try to the new sessionless keywords in 0.9
