### ISSUE TITLE
Status Code 422 using new POST On Session keyword

### ISSUE THREAD

**Issue by Se7enquick** [MarketSquare/robotframework-requests#323]
I`m facing an issue while refactoring the project with new [RequestName] On Session keywords. Here is the example:

```Post Now
    [Arguments]  ${AUCTION_NAME}
     
    ${ACTION_START_TIME}=  Get Time  format=timestamp  time_=UTC + 2s

    Create Session      alias   %{PROCEDURE_URL}   verify=true
    &{headers_post}=    Create Dictionary  Authorization=auction_token  Content-Type=application/json
    Import Variables    ../fixtures/${AUCTION_NAME}.py  init_auction
    
    Set To Dictionary   ${init_auction["auctionPeriod"]}  startDate  ${ACTION_START_TIME}
    ${RESP} =  POST On Session  alias  /api/procedures  data=${init_auction}  headers=${HEADERS_POST}  expected_status=201
    ${ID} =  Get From Dictionary  ${resp.json()}  id
    Set Suite Variable  ${ID}  ${ID}
```
This returns me 422 status code. But if I replace POST On Session with deprecated Post Request - it works properly. Did I miss smth?

**Comment by lucagiove** [comment]
If the content type is a json I suggest you to use the parameter  `json=` instead of `data=` 0.8 version does not encode data based on the headers it relies only on the original requests library logic.

Reopen if doesn't work.
