### ISSUE TITLE
Question: Keyword definition and intellisense in visual studio code

### ISSUE THREAD

**Issue by Franz333** [MarketSquare/robotframework-requests#327]
**Description**

I would like to add the keyword definition to visual studio code and access it with the usual ctrl + space.

I am using the [Robot Framework Intellisense](https://marketplace.visualstudio.com/items?itemName=TomiTurtiainen.rf-intellisense) from Tomi Turtiainen which allows me to import third party library.

Is there a json file with the keywords definition somewhere that I could use in vscode? I did not manage to find a file inside the Python Lib\site-packages dir..

NB: the definitions are showing perfectly within RobotFramework. 

Thank you

**Comment by lucagiove** [comment]
Hi it doesn't seem that maintained i know @Snooz82 integrated more libraries https://marketplace.visualstudio.com/items?itemName=Snooz82.rf-intellisense 
I don't know how he got the json, I think from the documentation, I'd be happy to help also because I'm releasing 0.9 with new keywords.

**Comment by Snooz82** [comment]
@Franz333 do not use Intellisense. Also not my Fork. Both are outdated!!!

the plugin Robot Framework Language Server is much much better. With Autocompletion and everything!
https://marketplace.visualstudio.com/items?itemName=robocorp.robotframework-lsp

**Comment by Franz333** [comment]
@lucagiove @Snooz82 Hi guys, ok thanks a lot for your help.. I am gonna switch to RF Language Server and see how it goes.. Have a nice day

**Comment by Franz333** [comment]
Hi guys,
I closed this issue too early. 
Installed the extension you adivsed me. I have a question..
How do I deactivate the info square with definition on hover? I would like it to appear only on deman via a shortcut.
It is appearing everytime my mouse is over a keyword.. really annoying.
Thanks a lot

**Comment by lucagiove** [comment]
Ok but I don't think this is an issue related to this project :)
Have you instead been able to have requests autocomplete on latest version?

**Comment by Franz333** [comment]
you are right, sorry about that.. I have the 0.9 version and autocomplete is on indeed

**Comment by lucagiove** [comment]
Cool!
