### ISSUE TITLE
Unable to send "#" as a query parameter in GET requests

### ISSUE THREAD

**Issue by shrinivasbb** [MarketSquare/robotframework-requests#331]
When '#" character is passed to the URL as query param with proper escape characters GET request is sent with empty param.

Using Template for testing different query params:

*** Keywords ***
Verify for a given ${param} response is success
     Create Session     testparam               url=http://xxxx.com?param=${param}     headers=${headers}    auth=${auth}
    ${resp}            Get On Session               testparam        ${EMPTY}
    Status Should Be    ${resp}    200

*** Test Cases ***
Test request URL with different query params
     [Template].    Verify for a given ${param} response is success
     ${EMPTY}#
     \#

For both the params # is not send in the request URL.

All the other characters can be used except "#".

**Comment by SunilKumarGU** [comment]
Use hexa value instead of '#' i.e %23. It might work. It worked for me.

**Comment by shrinivasbb** [comment]
Yes that is a workaround I tried with that already. But this is an issue.

**Comment by shrinivasbb** [comment]
> Use hexa value instead of '#' i.e %23. It might work. It worked for me.

Yes that is a workaround I tried with that already. But this is a valid issue.

**Comment by lucagiove** [comment]
I don't quite understand the example
