### ISSUE TITLE
disable ssl verification

### ISSUE THREAD

**Issue by christophehenry88** [MarketSquare/robotframework-requests#333]
Hello, 

Im creating a session with verify=${False}, but im always getting the error body=526 Invalid SSL Certificate when i post a request. 

Is the verify option really working?

**Comment by lucagiove** [comment]
It should be working but it's a verification on the client side for the server side certificate.
Maybe your error is from server about a client certificate.

**Comment by christophehenry88** [comment]
ok thanks, is it possible to use cer file? or its only pem?
