### ISSUE TITLE
FAIL : ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

### ISSUE THREAD

**Issue by nixuewei** [MarketSquare/robotframework-requests#336]
the same api
use robotframework-requests==0.6.5 and request==2.23.0, it can get response correctly
but if use robotframework-requests==0.9.0 ,it get below error
20210716 15:41:37.148 :  FAIL : ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by nixuewei** [comment]
it seems not the version issue. I put the same script into stg, it can call correct. but if call on local, it has this issue.

**Comment by lucagiove** [comment]
I'm sorry never saw similar errors.
