### ISSUE TITLE
403 Forbidden error while connecting to a server from Jenkins

### ISSUE THREAD

**Issue by SahithKumarrko** [MarketSquare/robotframework-requests#341]
Hi Team,

I am working on a project to automate a Trade Brokerage system of a client. I need to connect to a server and perform few actions.
I was able to connect from inside the client network, but i was not able to connect from the client's jenkins node. We checked the network connectivity and proxy settings everything is good. We also checked from a java script to connect to the server that also worked. But we were not able to do it using RobotFramework Requests library.

Here is the log of the robot script executed on jenkins node.
![error](https://user-images.githubusercontent.com/36582308/133427519-31933f3d-4a1a-403f-a4a3-65dab36a89be.jpg)

Please can you help me to resolve this issue.

Thanks.
Sahith

**Comment by lucagiove** [comment]
I believe there is something wrong with authentication / authorization in your network most probably not related to Requests.
