### ISSUE TITLE
Inaccurate timeout kwarg description or incorrect handing of it

### ISSUE THREAD

**Issue by SX91** [MarketSquare/robotframework-requests#344]
`timeout` is described to be either a float or tuple of two floats. Unfortunately, `timeout` from kwargs is passed directly to `_get_timeout`, which returns None or float.

Is it intentional? Or am I using the API incorrectly?

**Comment by lucagiove** [comment]
You are right currently this library is reducing the original library api only to single float variable instead of a tuple, I'll have a look into this.
