### ISSUE TITLE
No keyword GET POST PUT PATCH found in Requests Lib

### ISSUE THREAD

**Issue by kattinum** [MarketSquare/robotframework-requests#347]
Hello, 
 I installed the requestLib 0.9.2 and need to use kw GET, POST, PUT, PATCH but they seemed not found in library file. I'm not sure they're still available to use or not because I still see info in keyword manual. 

Any suggestion for this issue?

Error message:
No keyword with name 'GET' found. (other KWs show in similar msg)

**Comment by lucagiove** [comment]
Strange keywords are there :)
