### ISSUE TITLE
KW for sessionless

### ISSUE THREAD

**Issue by kattinum** [MarketSquare/robotframework-requests#348]
Hello,
 I’m looking for sessionless kws as what’s new in 0.9 version. I saw them in the guide document but they do not work. Do those kws work really?

thank you

**Comment by lucagiove** [comment]
Sure they work I don't see the point, what error do you get?

**Comment by kattinum** [comment]
I got no keywords such as POST, GET and so on but any session kws work normally such as Get on session etc. I try to check in lib but I don’t see code there.  Did I miss anything?

**Comment by lucagiove** [comment]
Here is the code: https://github.com/MarketSquare/robotframework-requests/blob/b70df43fece9b9eaae3f4e9b101443bcad15ce8b/src/RequestsLibrary/RequestsKeywords.py#L155

**Comment by kattinum** [comment]
I found this lib with code but i don’t know it shows no keyword when I run a script. Any idea to solve with this issue?
