### ISSUE TITLE
Get the response time of a request returned in the response in keywords GET/POST On Session

### ISSUE THREAD

**Issue by jgdevrennes** [MarketSquare/robotframework-requests#350]
It would be a good feature to have inside keywords "GET On Session" and "POST On Session" the response time of a request returned in the response or else.

Is this planned in your backlog ?

**Comment by lucagiove** [comment]
I think this information is already available in the response object using the [elapsed](https://docs.python-requests.org/en/latest/api/#requests.Response.elapsed) property.
