### ISSUE TITLE
'file-tuple' reported as a kwarg in the documentation

### ISSUE THREAD

**Issue by fabiodellagiustina** [MarketSquare/robotframework-requests#356]
I would need to upload a YAML file via a POST request.

From the [documentation](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#:~:text=multipart%20encoding%20upload.-,file%2Dtuple,-can%20be%20a), I'm trying the following:
`${response}    POST    https://abc.xyz/endpoint    file-tuple=('file', ${fileobj}, 'application/x-yaml')    verify=${False}`
But I get the following error:
`TypeError: request() got an unexpected keyword argument 'file-tuple'`

Robot Framework 5.0.1 (Python 3.9.10 on linux)

**Comment by fabiodellagiustina** [comment]
I got it to work with the following:
`${response} POST https://abc.xyz/endpoint files=${{ {'file': ('file', $fileobj, 'application/x-yaml')} }} verify=${False}`

Note that I was not aware of how to create a tuple in Robot. Thanks to https://stackoverflow.com/questions/65922892/how-to-create-a-list-of-tuples-without-each-pair-being-converted-to-string-in-ro.

However, the [RequestsLibrary documentation](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#:~:text=multipart%20encoding%20upload.-,file%2Dtuple,-can%20be%20a) misled me by reporting `file-tuple` as a kwarg, while it should be part of the above kwarg, `files`. (Reference: https://requests.readthedocs.io/en/latest/api/)

This should be fixed in the doc.

**Comment by lucagiove** [comment]
fixed in 40f03cd2a425fdb249a60d3dfa50f6ab7e9eadcb
