### ISSUE TITLE
Allow_redirection parameter is misleading

### ISSUE THREAD

**Issue by hernandik** [MarketSquare/robotframework-requests#360]
I spend sometime trying to disable "allow_redirection" of my POSTs requests, until I identify only one place where it as clear that I had to use '${False}' instead o 'False'. So I decide to create a simple fix in that documentation, to help other not to get caught on the same problems that I did. Below the fix suggestion.
https://github.com/MarketSquare/robotframework-requests/pull/359

**Comment by lucagiove** [comment]
Thank you! Have you reviewed all the keywords to see whether documentation always use ${False/True} instead of the python syntax False/True?
