### ISSUE TITLE
Decorators hide arguments for keywords, breaking intellisense for Vscode and robot LSP 

### ISSUE THREAD

**Issue by Serhiy1** [MarketSquare/robotframework-requests#367]
Using the robotframework-requests library with the Robot language server plugin for vs code. I have noticed that auto-complete does is not aware of the arguments for all of the keywords. instead, it reports `*args and **kwargs`. 

![image](https://user-images.githubusercontent.com/28574129/204778398-ee443de8-7ee1-47c2-b62d-018cf0f00eeb.png)

This is due to the decorator functions `warn_if_equal_symbol_in_url_on_session` and `warn_if_equal_symbol_in_url_session_less` not shadowing the original function signature. 

Adding `decorator.__signature__ = inspect.signature(func)`  inside the two wrapping functions fixes this issue. 

![image](https://user-images.githubusercontent.com/28574129/204779271-2c9a56e3-c41d-4949-9006-8c35fb3e854e.png)

Alternatively, we can get rid of the  manual assignments and user the warps decorator from the standard functools library

**Comment by lucagiove** [comment]
closed like the PR
