### ISSUE TITLE
The x-www-form-urlencoded Client authentication failed

### ISSUE THREAD

**Issue by mayaugusto7** [MarketSquare/robotframework-requests#373]
Hello guys!

I saw the examples in link https://github.com/MarketSquare/robotframework-requests/blob/master/atests/testcase.robot , but not working for me. 

I send a request using Postman is work normally.

I am using RED IDE, when run a robot test,  
the response is ` body={"error_description":"Client authentication failed","error":"invalid_request"} `,
but credentials and url are correct.

Has anyone had this problem?

**Comment by lucagiove** [comment]
I think the problem is specific of your request.
You better ask in RF forum.
