### ISSUE TITLE
Descriptions for PUT and PATCH cointain the same text

### ISSUE THREAD

**Issue by Futhark1988** [MarketSquare/robotframework-requests#374]
[PATCH](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#PATCH)

**Documentation**
Sends a PUT request.

The endpoint used to send the request is the url parameter, while its body can be passed using data or json parameters.

data can be a dictionary, list of tuples, bytes, or file-like object. If you want to pass a json body pass a dictionary as json parameter.

By default this keyword fails if a status code with error values is returned in the response, this behavior can be modified using the expected_status and msg parameters, read more about it in [Status Should Be](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#Status%20Should%20Be) keyword documentation. In order to disable this implicit assert mechanism you can pass as expected_status the values any or anything.

Other optional requests arguments can be passed using **kwargs see the [GET](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#GET) keyword for the complete list.
 
###############################################################

[PUT](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#PUT)

**Documentation**
Sends a PUT request.

The endpoint used to send the request is the url parameter, while its body can be passed using data or json parameters.

data can be a dictionary, list of tuples, bytes, or file-like object. If you want to pass a json body pass a dictionary as json parameter.

By default this keyword fails if a status code with error values is returned in the response, this behavior can be modified using the expected_status and msg parameters, read more about it in [Status Should Be](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#Status%20Should%20Be) keyword documentation. In order to disable this implicit assert mechanism you can pass as expected_status the values any or anything.

Other optional requests arguments can be passed using **kwargs see the [GET](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#GET) keyword for the complete list.

**Comment by lucagiove** [comment]
fixed
