### ISSUE TITLE
File Descriptor Not Closed For File Parameter

### ISSUE THREAD

**Issue by blaw859** [MarketSquare/robotframework-requests#378]
In RequestsKeywords.py there is a comment on line 51 `# file descriptors should be closed for files parameter as well`

As far as I am aware this is not happening, for example if you open a file for streaming, put it in a tuple with its filename, then in a dictionary where the name maps to this tuple. If you passed this dictionary to the PUT request using kwargs, `files=my_dict` the file descriptor for the file object created would never be closed

_Apologies if this issue already exists elsewhere as the comment seems to imply it would, however I could not find it_

**Comment by lucagiove** [comment]
I think that I should have added a FIXME prefix, I don't recall but probably I added it when I discover that file descriptors can be passed to files parameters as well. Indeed the commit where I added it is where I used this feature for a test.

**Comment by lucagiove** [comment]
try with the new version and let me know
