### ISSUE TITLE
"Status Should Be" uses last request even if a response is provided

### ISSUE THREAD

**Issue by apallier** [MarketSquare/robotframework-requests#383]
Version: 0.9.2 (but should exit in every versions until now)

# Steps to reproduce
Here a minimal code reproducing the problem:

```robotframework
*** Settings ***
Library    RequestsLibrary

*** Test Cases ***
Test
    ${response_error}=     GET    https://www.google.com/404    expected_status=any
    ${response_ok}=     GET    https://www.google.com    expected_status=any
    Status Should Be    404    ${response_error}
```

# Actual result
Keyword `Status Should Be` fails:

```
==============================================================================
Bug Requests Library                                                          
==============================================================================
Test                                                                  | FAIL |
Url: https://www.google.com/ Expected status: 200 != 404
------------------------------------------------------------------------------
Bug Requests Library                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
```

# Actual result
Keyword `Status Should Be` should pass because response `${response_error}` is actually a 404 error

# Investigation
1. It seems that a Requests Response in error is considered as "False". [See this code](https://github.com/psf/requests/blob/839a8edec37c81a18ac8332cfbd44f44e1ae6206/src/requests/models.py#L730)

2. And so the following code takes the "last response" if the Response is in error (the response provided in parameter is ignored): [See this code](https://github.com/MarketSquare/robotframework-requests/blob/e4291b7fd022682e08a6263dc91f22e9689b5fd7/src/RequestsLibrary/RequestsKeywords.py#L119C1-L121C59) :

```python
@keyword("Status Should Be")
def status_should_be(self, expected_status, response=None, msg=None):
    if not response:
        response = self.last_response
    self._check_status(expected_status, response, msg)
```

**Comment by lucagiove** [comment]
Ouch, thanks for the detailed report I'll have a look

**Comment by apallier** [comment]
Thanks for the fix 👍
