### ISSUE TITLE
 RequestLibrary Post On session fail with  "is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8." when use arabic char but  Post request pass 

### ISSUE THREAD

**Issue by skoroghly** [MarketSquare/robotframework-requests#399]
RequestLibrary Post On session fail with  "is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8." when use arabic char
but  Post request pass

**Comment by lucagiove** [comment]
Sorry but there are not enough information to process this issue.
We need more data, examples maybe a failing test that we can debug.
