### ISSUE TITLE
POST is not mentioned in the "DEFAULT_ALLOWED_METHODS" list 

### ISSUE THREAD

**Issue by RahulThakurLocus** [MarketSquare/robotframework-requests#402]
We have retry for below requests but POST is not included in that list.
 Why are we not considering the POST for retry ?

```
 #: Default methods to be used for ``allowed_methods``
    DEFAULT_ALLOWED_METHODS = frozenset(
        ["HEAD", "GET", "PUT", "DELETE", "OPTIONS", "TRACE"]
    )
```

**Path of file**:  .venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/retry.py

**Comment by lucagiove** [comment]
This is the default of original request library and the reason is that POST and PATCH are not idempotent so it's not safe to retry them by default.
