### ISSUE TITLE
To have the ability to use SSL without verifying certificates

### ISSUE THREAD

**Issue by mikelee84** [MarketSquare/robotframework-requests#5]
Is there is a possibility to have create session keyword to remove SSL verification cert when creating a HTTPS session?

**Comment by shaib25** [comment]
Hi,
When using create session keyword, with verify=False, to remove SSL verification cert, request fails on [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
When sending the same request with curl --insecure, it works fine. 
Is it possible to allow connections to SSL sites without x509 certs as well?

**Comment by vkosuri** [comment]
@shaib25 Did you tried the same request using python requests?

**Comment by shaib25** [comment]
When using Process library - Run curl with --insecure flag - it works well, but when working with RequestLibrary, e.g.,  Post Request - it fails.
