### ISSUE TITLE
dealing with expanded dictionary key-value 

### ISSUE THREAD

**Issue by lunarman** [MarketSquare/robotframework-requests#8]
hi, 
first off, great work on integrating this function into robot.
however, there's a slight problem that i'm running into with this lib.
is there a way to deal with JSON data whose key has extensive nested key-value pairs or even deeper nested objects?
say, by introducing a known tag or something?
e.g.:
{"data":[{"stuff":[
    {"onetype":[
        {"id":1,"name":"John Doe"},
        {"id":2,"name":"Don Joeh"}
    ]},
    {"othertype":[
        {"id":2,"company":"ACME"}
    ]}]
},{"otherstuff":[
    {"thing":
        [[1,42],[2,2]]
    }]
}]}

thanks a lot!!

**Comment by lucagiove** [comment]
Pass a dictionary to the json parameter
