### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by swapnilpatne** [MarketSquare/robotframework-requests#9]
Can you please provide API documentation something like this http://peritus.github.io/robotframework-httplibrary/HttpLibrary.html

**Comment by dmiqueli** [comment]
Hi Bulkan

I need an example using Post request to upload a zip file. I'm having a 500 error code every time I try

**Comment by bulkan** [comment]
@dmiqueli This sample test should help

https://github.com/bulkan/robotframework-requests/blob/master/tests/testcase.robot#L196
